### ISSUE TITLE
Still under development ?

### ISSUE THREAD

**Issue by looped-monk** [justkawal/tenor#1]
Hi Kawal,
Narayanan here.

Just bumped into your tenor repo. it is still under development. Any idea when it might be available ? there is no alternative to giphy plugin avaliable yet for dart. Waiting for your reply. Have a nice day.

**Comment by justkawal** [comment]
@narayanan-ka, Thanks for putting this to light

Yes, it was under development and now it is published on https://pub.dev/packages/tenor

See the full documentation on - [Documentation](https://github.com/justkawal/tenor#donate-)

Don't forget to become [Patron Member](https://patreon.com/justkawal)

Long Live Open Source,
