### ISSUE TITLE
Language documentation

### ISSUE THREAD

**Issue by obrunsmann** [justkawal/tenor#6]
As discussed in #5 adding the available languages to the docs

So basically the docs say:
> specify default language to interpret search string; xx is ISO 639-1 language code, _YY (optional) is 2-letter ISO 3166-1 country code

This is the list of available languages:
```
Albanian
Arabic
Bengali
Cantonese
Catalan
Croatian
Czech
Danish
Dutch
English
Farsi
Finnish
French
German
Greek
Hebrew
Hindi
Hungarian
Indonesian
Italian
Japanese
Korean
Malay
Norwegian (Bokmal)
Norwegian (Nynorsk)
Polish
Portuguese
Romanian
Russian
Simplified Chinese
Slovak
Spanish
Swedish
Tagalog
Thai
Traditional Chinese
Turkish
Ukrainian
Urdu
Vietnamese
```
_Edit: Ordered list by name_
Source: https://tenor.com/gifapi/documentation#localization

**Comment by justkawal** [comment]
@obrunsmann 
I also had a look on it, and I had mapped the language codes with their country names in local changes.

A push will be coming up sooner.

**Comment by justkawal** [comment]
Fixed : https://github.com/justkawal/tenor/commit/17b64b729e8aa4923b7a4f756c10dcf09578fd66

It has the Languages also and is available on https://pub.dev/packages/tenor

`tenor: 1.0.9`
