### ISSUE TITLE
Register Share

### ISSUE THREAD

**Issue by obrunsmann** [justkawal/tenor#7]
I just missed the register share action in the SDK: https://tenor.com/gifapi/documentation#endpoints-registershare

So I could try to contribute this endpoint maybe this week / weekend.

**Comment by justkawal** [comment]
@obrunsmann 
Awesome I would be waiting. 🥳 

And yeah I will be discontinuing the non null-safe code and making master as null-safe and will be working on it only.

**Comment by obrunsmann** [comment]
Okay great, so we are not yet un null-safe (cause of too many deps 🙄) so I would implement that on the current branch without null safe.
Are you already working on null-safety for this package? Maybe we could document this into an issue :))

**Comment by justkawal** [comment]
@obrunsmann 
Null-safe version is already published.

**Comment by obrunsmann** [comment]
Aah sorry, I see. Misunderstood this

**Comment by justkawal** [comment]
@obrunsmann 

It's okay, Chillax, It happens

**Comment by justkawal** [comment]
@obrunsmann I have implemented registershare functionality. I hope you it might same you some time,

Also I have done some changes in whole package so as to easily manage the functions internally

**Comment by obrunsmann** [comment]
Awesome, thank you!

**Comment by justkawal** [comment]
@obrunsmann 
The register share is working fine but from Tenor's server sometimes it sends empty response on purpose, I don't know why,

So, for to use the registerShare be sure to generate the anon_id from the generateAnonId() and then after getting that anon_id pass it to the functions where you are doing any search query or any query from the user's text input.

then you can register share on the gif objects and also on the searching of the auto-complete and search-suggestions text terms.

Thanks
Happy to help.
