### ISSUE TITLE
Lagging gif movements when many gifs are loaded

### ISSUE THREAD

**Issue by ScottLee97** [justkawal/tenor#8]
Hi, thank you very much for this package!

When I requested more than 100 gifs and displayed them using grid view on a scrollable page, the gifs that are shown starts to lag and the gif movements are no longer smooth. Do you happen to what is the reason for the lag? Do you know how I can improve its performance?

Thanks in advance!

**Comment by justkawal** [comment]
1) Try to load the previewThumbnails only and try to run in release/profile mode, which is much faster and realistic case when app will be launched

2) Try using builder methods of GridView/ListView which helps in lazy loading and thus saves resources.

For further queries:

**Please try asking this in Flutter's main Github repo as Tenor does not depends on Flutter and hence have nothing to deal with performance.**
